kitherder/matchmaker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kitherder.views.home', name='home'),
    # url(r'^kitherder/', include('kitherder.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', 'matchmaker.views.myprojects'),
	url(r'^myprojects', 'matchmaker.views.myprojects'),
	url(r'^submitproject', 'matchmaker.views.submitproject'),
	url(r'^searchproject', 'matchmaker.views.searchproject'),
	url(r'^managedivision', 'matchmaker.views.managedivision'),
	url(r'^project/(?P<project_id>\d+)/$', 'matchmaker.views.projectdetail'),
	url(r'^project/(?P<project_id>\d+)/edit', 'matchmaker.views.projectedit'),
	url(r'^menteefinder', 'matchmaker.views.searchmentee'),
	url(r'^mentorfinder', 'matchmaker.views.searchmentor'),
	url(r'^milestoneadd', 'matchmaker.views.milestoneadd'),
	url(r'^milestoneedit/(?P<milestoneID>\d+)/$', 'matchmaker.views.milestoneedit'),
	url(r'^browserid/', include('django_browserid.urls')),
)

urlpatterns += staticfiles_urlpatterns()

kitherder/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kitherder.views.home', name='home'),
    # url(r'^kitherder/', include('kitherder.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	url(r'^admin/', include(admin.site.urls)),
	(r'^$', include('entrance.urls')),
	(r'^entrance/', include('entrance.urls')),
	(r'^userprofile/', include('userprofile.urls')),
	(r'^matchmaker/', include('matchmaker.urls')),
	
)

kitherder/matchmaker/models.py
from django.db import models
from django.contrib.auth.models import User
# Here is the complete model for kitherder including matchmaker and other apps.

class Division(models.Model):
	division_name = models.CharField(max_length=50, unique=True)
	mozillian_group = models.CharField(max_length=50, unique=True, blank=True)
	
	def __unicode__(self):
		return self.division_name
		
	class Meta:
		ordering = ('division_name',)
	
	
class Mentee(models.Model):
	user_id = models.ForeignKey(User, unique=True)
	is_looking = models.BooleanField()
		
	def __unicode__(self):
		return self.user_id.username	
	
class Mentor(models.Model):
	user_id = models.ForeignKey(User, unique=True)
	
	
	def __unicode__(self):
		return self.user_id.username

class Coordinator(models.Model):
	user_id = models.ForeignKey(User, unique=True)
	division_id = models.ManyToManyField(Division)
	# ASSUMPTION: coordinator comes into the system already vouched. Probably admin will add him/her in
	
	def __unicode__(self):
		return self.user_id.username	
	
class Projectstatus(models.Model):
	status = models.CharField(max_length=30, unique=True)
	deprecated = models.BooleanField()
	def __unicode__(self):
		return self.status

# ASSUMPTION: Project:Mentor:Mentee is a one-to-one-to-one relationship	
class Project(models.Model):
	project_name = models.CharField(max_length=70, unique=True)
	parent_project_id = models.ForeignKey('self', null=True, blank=True, verbose_name="Parent project")
	division_id = models.ForeignKey(Division, verbose_name="Division")
	mentor_id = models.ForeignKey(Mentor, null=True, blank=True)
	mentee_id = models.ForeignKey(Mentee, null=True, blank=True)
	approved= models.BooleanField()
	approved_by = models.ForeignKey(Coordinator, null=True, blank=True)
	project_description = models.CharField(max_length=300)
	terms_agree = models.BooleanField()
	project_status_id = models.ForeignKey(Projectstatus)
	skills_required = models.CharField(max_length=300)
	
	def __unicode__(self):
		return self.project_name

class MenteeInterestInProject(models.Model):
	project_id = models.ForeignKey(Project)
	mentee_id = models.ForeignKey(Mentee)
			
class Milestone(models.Model):
	project_id = models.ForeignKey(Project)
	milestone_name = models.CharField(max_length=100)
	milestone_status = models.CharField(max_length=80)
	milestone_comments = models.CharField(max_length=500)
	start_date = models.DateTimeField()
	projected_end_date = models.DateTimeField()
	completion_date = models.DateTimeField(null=True, blank=True )
	
	def __unicode__(self):
		return self.milestone_name
	
	

kitherder/matchmaker/forms.py
from django.forms import ModelForm, Textarea, HiddenInput, DateInput
from django import forms
from matchmaker.models import Project, Division, Coordinator, Mentor, Mentee, Milestone


class ProjectForm(ModelForm):
	class Meta:
		model = Project

		
class MilestoneForm(ModelForm):
	class Meta:
		model = Milestone
		

class MentorMenteeProjectForm(ProjectForm):
	terms_agree = forms.BooleanField(label='I agree to these terms', required=True)
	class Meta(ProjectForm.Meta):
		exclude = ('mentor_id', 'mentee_id', 'approved', 'approved_by', 'project_status_id')
		widgets = {
			'project_description': Textarea(attrs={'cols': 80, 'rows': 10}),
        }

class CoordinatorProjectForm(ProjectForm):
	class Meta(ProjectForm.Meta):
		exclude = ('mentor_id', 'mentee_id', 'approved_by', 'terms_agree')
		widgets = {
			'project_description': Textarea(attrs={'cols': 80, 'rows': 10}),
        }
		
class MenteeEditProjectForm(ProjectForm):
	class Meta(ProjectForm.Meta):
		exclude = ('mentor_id', 'mentee_id', 'division_id', 'terms_agree', 'approved', 'approved_by', 'project_status_id')
		widgets = {
			'project_description': Textarea(attrs={'cols': 80, 'rows': 10}),
        }

class MentorEditProjectForm(ProjectForm):
	class Meta(ProjectForm.Meta):
		exclude = ('mentor_id', 'mentee_id', 'division_id', 'terms_agree', 'approved', 'approved_by')
		widgets = {
			'project_description': Textarea(attrs={'cols': 80, 'rows': 10}),
        }	

class CoordinatorEditProjectForm(ProjectForm):
	class Meta(ProjectForm.Meta):
		exclude = ('mentor_id', 'mentee_id', 'terms_agree', 'approved', 'approved_by')
		widgets = {
			'project_description': Textarea(attrs={'cols': 80, 'rows': 10}),
        }	
		
class MentorMenteeMilestoneForm(MilestoneForm):
	class Meta(MilestoneForm.Meta):
		widgets = {
			'project_id': HiddenInput,
			'milestone_comments': Textarea(attrs={'cols': 30, 'rows': 10}),
			'start_date': DateInput(attrs={'class': 'date'}),
			'projected_end_date': DateInput(attrs={'class': 'date'}),
			'completion_date': DateInput(attrs={'class': 'date'}),
        }

kitherder/matchmaker/views.py
# Create your views here.

from django.template import Context, loader
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.template import RequestContext
from django import forms
from django.db.models import Q
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect

from matchmaker.models import Project, Division, Coordinator, Mentor, Mentee, Projectstatus, MenteeInterestInProject, Milestone
from matchmaker.forms import ProjectForm, MentorMenteeProjectForm, CoordinatorProjectForm, MenteeEditProjectForm, MentorEditProjectForm, CoordinatorEditProjectForm, MentorMenteeMilestoneForm

import json
import requests

from matchmaker.utils import findUserRole, belongToProject, findDivisionsCorrespondingCoordinator, findDivisionsCorrespondingMentorMentee,getMozillianDataByUser, getMozillianGroupsbyUser, getVouchedMembersofDivision, getMozillianSkillsByUser


	
# some extra forms #

class SearchForm(forms.Form):
    searchterm = forms.CharField(max_length=500, required=False)
    noncompleted = forms.BooleanField(initial=True,required=False)
    matchskills = forms.BooleanField(required=False)
    mozilliangroups = forms.BooleanField(required=False)
	
class SearchMenteeForm(forms.Form):
	project = forms.IntegerField(widget=forms.HiddenInput)
	searchterm = forms.CharField(max_length=500,required=False)
	matchskills = forms.BooleanField(required=False)
	
class SearchMentorForm(forms.Form):
	project = forms.IntegerField(widget=forms.HiddenInput)
	searchterm = forms.CharField(max_length=500,required=False)
	matchskills = forms.BooleanField(required=False)
	
class DivisionGroupForm(forms.Form):
	division = forms.IntegerField(widget=forms.HiddenInput)

	def __init__(self,*args,**kwargs):
		email = kwargs.pop("email")     # client is the parameter passed from views.py
		super(DivisionGroupForm, self).__init__(*args,**kwargs)
		self.fields['mozilliangroup'] = forms.ChoiceField(label="", choices=[(item, item) for item in getMozillianGroupsbyUser(email)])
		

# end of extra forms #	
	
	
	
	
@login_required
def myprojects(request):
	role = findUserRole(request.user.email)	
	if role == "":
		return redirect('/entrance/register/', context_instance=RequestContext(request))
	
	if role == "mentor":
		myprojectslist = Project.objects.filter(mentor_id__user_id__email=request.user.email)
	elif role == "mentee":
		myprojectslist = Project.objects.filter(mentee_id__user_id__email=request.user.email)
	elif role == "coordinator":
		divisionList = findDivisionsCorrespondingCoordinator(request.user.email)
		myprojectslist = Project.objects.filter(division_id__in = divisionList)
		
		if request.method == 'POST' and "approveproject" in request.POST:
			p = Project.objects.get(pk=request.POST['project'])
			c = Coordinator.objects.get(user_id__email=request.user.email)
			p.approved= True
			p.approved_by = c
			p.save()

	return render_to_response('matchmaker/templates/myprojects.html', {'myprojectslist': myprojectslist, 'role': role}, context_instance=RequestContext(request))	


@login_required	
def searchproject(request):
	# ASSUMPTION: By default, everyone can search and see everyone else's project (unless advanced search options/filters are used)
	
	role = findUserRole(request.user.email)
	if role == "":
		return redirect('/entrance/register/', context_instance=RequestContext(request))

	
	if request.method == 'POST':
		searched = 1;
		form = SearchForm(request.POST)
		if form.is_valid():
			searchterm = form.cleaned_data['searchterm']

			if searchterm == '':
				resultprojectslist = Project.objects.all()		
			else:
				resultprojectslist = Project.objects.filter(Q(division_id__division_name__icontains=searchterm) | Q(project_name__icontains=searchterm) | Q(project_description__icontains=searchterm) | Q(skills_required__icontains=searchterm) | Q(parent_project_id__project_name__icontains=searchterm))
			
			divisionerror = "";
			skillserror = "";
			# advanced option: refine by if only in user's group (warning: if user is not in group, will return no results)
			if form.cleaned_data['mozilliangroups']:
				if role == 'coordinator':
					division = findDivisionsCorrespondingCoordinator(request.user.email)[0]
					resultprojectslist = resultprojectslist.filter(division_id = division.pk)
				else:
					try:
						userdivision = findDivisionsCorrespondingMentorMentee(request.user.email)		
						resultprojectslist = resultprojectslist.filter(division_id__in=[item.pk for item in userdivision])
					except Exception as e:
						divisionerror = "<li>Search result does not filter by divisions related to your Mozillian groups</li>"
			
			# advanced option: refine by showing non completed projects (default checked)
			if form.cleaned_data['noncompleted']:
				resultprojectslist = resultprojectslist.exclude(project_status_id__status = "completed")

			# advanced option: only matching user's skills (warning, if user have not entered skills in mozillian, will return no results)
			if form.cleaned_data['matchskills']:
				try:
					filter = Q()
					for skill in getMozillianSkillsByUser(request.user.email):
						filter	= filter | Q(skills_required__icontains = skill)
				
					resultprojectslist = resultprojectslist.filter(filter)
				except Exception as e:
					skillserror = "<li>Search result does not filter by your skills.</li>"
			
			print skillserror
			
			if divisionerror != "" or skillserror != "":
				error = "Mozillian is currently not available:<ul>"
				if divisionerror:
					error = error + divisionerror
				if skillserror:
					error = error + skillserror
				error = error + "</ul>"
				return render_to_response('matchmaker/templates/searchproject.html', {'resultprojectslist': resultprojectslist, 'role':role, 'form': form, 'error': error, 'searched': searched}, context_instance=RequestContext(request))
			
			
			return render_to_response('matchmaker/templates/searchproject.html', {'resultprojectslist': resultprojectslist, 'role':role, 'form': form, 'searched': searched}, context_instance=RequestContext(request))
			
			
	searched = 0;
	form = SearchForm()
	
	return render_to_response('matchmaker/templates/searchproject.html', {'form': form, 'role':role, 'searched': searched}, context_instance=RequestContext(request))


@login_required	
def projectdetail(request, project_id):
	status="nothing";
	role = findUserRole(request.user.email)
	if role == "":
		return redirect('/entrance/register/', context_instance=RequestContext(request))
	
	isbelong = belongToProject(request.user.email,project_id)
	
	if role == "coordinator":
		if request.method == 'POST' and "approveproject" in request.POST:
			p = Project.objects.get(pk=request.POST['project'])
			c = Coordinator.objects.get(user_id__email=request.user.email)
			p.approved= True
			p.approved_by = c
			p.save()
	
	

	theproject = Project.objects.get(pk=project_id)
	mycoordinatorlist = Coordinator.objects.select_related().filter(division_id=theproject.division_id)
	

	if request.method == 'POST' and 'deleteMilestone' in request.POST:
		m = Milestone.objects.get(pk=request.POST['milestone'])
		m.delete()
		status="deletedMilestone"
		
	# assume anyone can see the milestones list
	milestoneslist = Milestone.objects.select_related().filter(project_id=project_id)
	
	# check to see if user is a mentee and is not a member of the project, whether they have expressed interest already in the project
	expressedinterest = 0
	if not isbelong and role == "mentee":
		# if user has clicked on the express interest button
		if request.method == 'POST' and "expressinterest" in request.POST:
			mentee = Mentee.objects.get(user_id__email=request.user.email)
			interest = MenteeInterestInProject(project_id=theproject, mentee_id=mentee)
			interest.save()
		expressedinterest = MenteeInterestInProject.objects.filter(mentee_id__user_id__email=request.user.email,project_id=project_id).count()
		return render_to_response('matchmaker/templates/projectdetails.html', {'theproject': theproject, 'mycoordinatorlist': mycoordinatorlist, 'milestoneslist': milestoneslist, 'role': role, 'isbelong': isbelong, 'expressedinterest': expressedinterest, 'status': status}, context_instance=RequestContext(request))
	
	
	
	# check to see if user is a mentor and list all mentees who had expressed interest
	if (isbelong and role == "mentor") or role =="coordinator":
		# if user has clicked on select mentee to add a mentee from the "expressed interest" list
		# ASSUMPTION: mentors can add a mentee who has expressed interest in their project to the project but the triad still has to be approved_by coordinator
		# COROLLARY ASSUMPTION: a mentor can also add any mentee who is currently marked to be looking for a project (whether they have expressed interest or not)
		if request.method == 'POST' and "selectmentee" in request.POST:
			p = Project.objects.get(pk=request.POST['project'])
			m = Mentee.objects.get(user_id__email=request.POST['selectedmentee'])
			p.mentee_id = m
			p.save()
			theproject = Project.objects.get(pk=project_id)			
		
		expressedinterestlist = MenteeInterestInProject.objects.filter(project_id=project_id)

		return render_to_response('matchmaker/templates/projectdetails.html', {'theproject': theproject, 'mycoordinatorlist': mycoordinatorlist, 'milestoneslist': milestoneslist, 'role': role, 'isbelong': isbelong, 'expressedinterestlist': expressedinterestlist, 'status': status}, context_instance=RequestContext(request))

kitherder/matchmaker/templates/base.html
{% load browserid %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{% block title %}{% endblock %}</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">

<meta charset="utf-8">
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/redmond/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script src="{{ STATIC_URL }}js/tag-it.js" type="text/javascript" charset="utf-8"></script>


<link href="http://mozorg.cdn.mozilla.net/media/css/tabzilla-min.css" rel="stylesheet" />
<script src="https://browserid.org/include.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<link href="{{ STATIC_URL}}css/jquery.tagit.css" rel="stylesheet" type="text/css">

<!--[if !lte IE 7]><!-->
    <link rel="stylesheet" media="screen,projection,tv" href="//mozorg.cdn.mozilla.net/media/css/responsive-min.css?build=1ab6847" />
<!--<![endif]-->
<link rel="stylesheet" media="screen,projection,tv" href="//mozorg.cdn.mozilla.net/media/css/styleguide-min.css?build=1ab6847" />
<link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico">


<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"> <!-- FONTS for opensans -->
<link href="{{ STATIC_URL }}css/KitherderLayout.css" rel="stylesheet" type="text/css" />   <!-- my layout CSS with divs for layout and columns-->
<link href="{{ STATIC_URL }}css/Kitherder.css" rel="stylesheet" type="text/css" />   <!-- the look of kitherder colours fonts etc -->
<link href="{{ STATIC_URL }}css/tables.css" rel="stylesheet" type="text/css" />  <!-- implements table functionality --> 



<script language="JavaScript">
	function target_popup(form, popupcontent)
	{
		window.open(popupcontent, 'formpopup', 'scrollbars=1,locationbar=no,nmenubar=no,toolbar=no,status=no,width=600,height=500');
		form.target = 'formpopup';
	}
	
	$(document).ready(function(){
  		$("span.toggle").click(function(){
			$(".divInfo").slideToggle("fast");
		});
	});

	
</script>



</head>

<body>
<div id = "MainWrapper">
{% browserid_info %}
<div id="ContentWrapper">
<a href="https://www.mozilla.org/" id="tabzilla">mozilla</a>
<div class="authentication" style="padding-top: 10px">
	{% if user.is_authenticated %}
	  Logged in as <a href="/userprofile/">{{ user.email }}</a> | {% browserid_logout text='Logout' %}
	{% else %}
	  {% browserid_login text='' link_class='browserid-Login' %}
	{% endif %}
</div>
<div class="cleaner">&nbsp;</div>
<br>&nbsp;<br>
<div class="large" id="Title"><img src="{{ STATIC_URL }}images/logo.png" align="absmiddle" width="100">KitHerder</div> <!-- end title -->


<div id="Nav">
<div class="table"> <!-- start of table --> 
    <div class="table-row">
    	<span class="table-cell" style="border-bottom: none"> <a href="/matchmaker/myprojects/">My {% if role == "coordinator" %}Divisional {% endif %}Projects </a> </span> 
		<span class="table-cell" style="border-bottom: none"> <a href="/matchmaker/searchproject/">Search Projects</a></span> 
        <span class="table-cell" style="border-bottom: none"> <a href="/matchmaker/submitproject/">Submit Project</a></span> 
        {% if role == "coordinator" %}
        	<span class="table-cell" style="border-bottom: none"> <a href="/matchmaker/managedivision/">Manage Division</a></span> 
        {% endif %}
	</div>
</div> <!-- end table -->           
</div> <!-- end Nav -->


<div id="Content">
{% block content %}{% endblock %}
</div> <!-- end Content -->
</div> <!--end content wrapper -->

<div id="Footer">
<div id = "FooterWrapper">
<br />
<div style="float: left">
<a href="http://mozilla.org/"><img src="{{ STATIC_URL}}images/footer-mozilla.png"></a>
</div>
<div style="float: right">
Contribute to Kitherder. <a href="https://github.com/ygjb/kitherder">Make some changes.</a>
</div>
</div>
</div> <!-- end Footer -->
<script src="//mozorg.cdn.mozilla.net/tabzilla/tabzilla.js"></script>

{% browserid_js %}

</div> <!-- end main wrapper -->
</body>
</html>

kitherder/matchmaker/templates/basepopup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>{% block title %}{% endblock %}</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">

<link href="//mozorg.cdn.mozilla.net/media/css/tabzilla-min.css" rel="stylesheet" />
<script src="https://browserid.org/include.js" type="text/javascript"></script>

<!--[if !lte IE 7]><!-->
    <link rel="stylesheet" media="screen,projection,tv" href="//mozorg.cdn.mozilla.net/media/css/responsive-min.css?build=1ab6847" />
<!--<![endif]-->
<link rel="stylesheet" media="screen,projection,tv" href="//mozorg.cdn.mozilla.net/media/css/styleguide-min.css?build=1ab6847" />
<link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico">


<link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"> <!-- FONTS for opensans -->
<link href="{{ STATIC_URL }}css/KitherderLayout.css" rel="stylesheet" type="text/css" />   <!-- my layout CSS with divs for layout and columns-->
<link href="{{ STATIC_URL }}css/Kitherder.css" rel="stylesheet" type="text/css" />   <!-- the look of kitherder colours fonts etc -->
<link href="{{ STATIC_URL }}css/tables.css" rel="stylesheet" type="text/css" />  <!-- implements table functionality --> 

<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.11.0.min.js"> type="text/javascript"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
	$(document).ready(function() {
		$('.date').each(function() {
			$(this).datepicker({ dateFormat: 'yy-mm-dd' });
		});
	});
	
	$(document).ready(function(){
  		$("span.toggle").click(function(){
			$(".divInfo").slideToggle("fast");
		});
	});
</script>

</head>

<body>
<div id="ContentWrapper">

<div id="Content" style="margin-top: 20px;">
{% block content %}{% endblock %}
</div> <!-- end Content -->


<!--<div class="body" id="Footer">

</div> -->

</div> <!--end main wrapper -->

</body>
</html>

kitherder/matchmaker/templates/managedivision.html
{% extends "base.html" %}

{% block title%}KitHerder: Manage Division{% endblock %}

{% block content %}
	<h3>Manage Division</h3>

    <p><i>Identify which Mozillian group is used for managing mentors and mentees for your division.</i></p>
   	Current Mozillian group for {{ division }} division: 
   	{% if division.mozillian_group %}
   		{{ division.mozillian_group }}
   	{% else %}
   		No group yet
   	{% endif %}
   	
   	<br />&nbsp;<br />&nbsp;<br />
   	
   	<h4>Change the division's group</h4>
   	
   	{% if error %}
   		<p class="error">{{ error }}</p>
   	{% else %}
 	  	<form method="post" action="">{% csrf_token %}
			<label for="mozilliangroup" style="float: none">New group: </label>
			{{ form }}
			<input type="submit" name="submit" id="submit" value="Submit" class="button" />
		</form>
		<br />
		<p class="small"><i>Can't find the division you're looking for? Check to see if you are a member of that division. You can only see Mozillian groups that you are a member of here.</i></p>
	   
   	{% endif %}
   	
   	
{% endblock %}

kitherder/matchmaker/templates/menteefindersuccess.html
{% extends "basepopup.html" %}

{% block title%}KitHerder: Mentee Finder{% endblock %}


{% block content %}
	<script language="JavaScript">
		window.opener.location.reload(false);
		function close_popup()
		{
			window.close();
		}
	</script>

	You have successfully added {{ mentee }} to the {{ project_name }} project.
	
	<p align="center"><a href="#" onClick="close_popup()">close window</a></p>
		   
{% endblock %}

kitherder/matchmaker/templates/mentorfindersuccess.html
{% extends "basepopup.html" %}

{% block title%}KitHerder: Mentee Finder{% endblock %}


{% block content %}
	<script language="JavaScript">
		window.opener.location.reload(false);
		function close_popup()
		{
			window.close();
		}
	</script>

	You have successfully added {{ mentee }} to the {{ project_name }} project.
	
	<p align="center"><a href="#" onClick="close_popup()">close window</a></p>
		   
{% endblock %}

kitherder/matchmaker/templates/projectedit.html
{% extends "base.html" %}

{% block title%}KitHerder: Project Details{% endblock %}

{% block content %}
	<script typeimage="text/javascript">
	    $(document).ready(function() {
    	    $("#id_skills_required").tagit({allowSpaces: true});
    	});
	</script>

	<h2>Project Details</h2>
	
	{% if theproject %}
		<form method="post" action="">{% csrf_token %}
			<table>
			{{ submitform.as_table }}
			<tr><td>&nbsp;</td><td><input type="submit" name="submit" id="submit" value="Submit" class="button" /></td></tr>
			</table>
		</form>
	{% else %}
    	<p>Project does not exist</p>
	{% endif %} 
{% endblock %}

kitherder/matchmaker/templates/submitproject.html
{% extends "base.html" %}

{% block title%}KitHerder: Project Details{% endblock %}

{% block content %}
    	<script type="text/javascript">
	    $(document).ready(function() {
    	    $("#id_skills_required").tagit({allowSpaces: true});
    	});
	</script>

	<h2>Submit Project</h2>
	<br />
    {% if cannotsubmit %}
    	{% if cannotsubmit == 1 %}
    		As a mentor, you must join one of the Kitherder groups in Mozillian before you can submit a project. <a href="https://mozillian.org">Go join now.</a>
    	{% endif %}
    	{% if cannotsubmit == 2 %}
    		Divisions from Mozillian not available at this time. Please check <a href="https://mozillian.org">Mozillian</a>
    	{% endif %}
    {% else %} 
   		<form method="post" action="">{% csrf_token %}
			<table>
			{{ submitform.as_table }}
			<tr><td>&nbsp;</td><td><input type="submit" name="submit" id="submit" value="Submit" class="button" /></td></tr>
			</table>
		</form>
	{% endif %}
	   
{% endblock %}